// All user-facing copy for the Calls tool, EN + AR. Keep the two shapes identical.
export const STR = {
  en: {
    title: 'Private call', lead: 'Secure meetings — video, whiteboard, chat and files go straight between browsers. Only the initial handshake, never any data, touches our server.',
    yourName: 'Your name', start: 'Start call', askJoin: 'Ask to join', startOwn: 'Start your own call instead', shuffle: 'Random name', rememberName: 'Tick to remember your name', joining: 'Connecting…', checkingMeeting: 'Checking meeting…', shareInvite: 'Share invite',
    mic: 'Mic', cam: 'Camera', screen: 'Share screen', stopScreen: 'Stop sharing', screenUnsupported: 'Screen sharing isn’t supported on this device', screenFailed: 'Screen share failed', board: 'Whiteboard', chat: 'Chat', invite: 'Invite', leave: 'Leave',
    you: 'You', waiting: 'Waiting for others to join — share the invite.', clear: 'Clear', typeMsg: 'Message…', send: 'Send', noMessages: 'No messages yet', close: 'Close', reconnecting: 'Quiet — reconnecting…', dropFiles: 'Drop files to send, or tap',
    maximize: 'Maximise', restore: 'Restore', reactions: 'Reactions', dock: 'Panel', tags: 'Tags', addTag: 'Add a tag…', whoReacted: 'Reactions',
    copied: 'Invite link copied', copy: 'Copy link', copyDone: 'Copied!', shareQrUrl: 'Share QR + URL', shareHint: 'Share the link — people who open it appear here for you to let in.',
    lobbyList: 'Waiting in the lobby', admit: 'Let in', leftLobby: 'left', waitingHost: 'Waiting for the host to let you in…', cancel: 'Cancel',
    participants: 'Participants', endMeeting: 'End meeting', hangUp: 'Leave', sendFiles: 'Drop files', dropHere: 'Drop files to share with everyone', muteMe: 'Mute me', unmuteMe: 'Unmute',
    camOn: 'Turn camera on', camOff: 'Turn camera off', mutedBy: 'muted', muteThem: 'Mute for everyone', filesTitle: 'Files', noPreview: 'No preview — download to open', download: 'Download',
    devices: 'Devices', camera: 'Camera', microphone: 'Microphone', speaker: 'Speaker',
    hostGone: 'The host disconnected', endsIn: 'meeting ends in', ended: 'This meeting has ended or can’t be found.', newCall: 'Start a new call',
    youEnded: 'You have left the call', youEndedMeeting: 'You ended the meeting.', stillThere: (n: number) => `${n} ${n === 1 ? 'participant is' : 'participants are'} still there`, rejoin: 'Rejoin', createNew: 'Create a new meeting',
    joined: 'joined', left: 'left', editName: 'Edit your name', waitingToJoin: 'is waiting to join',
    notifyWhy: 'Get notified when someone joins — even when this tab is in the background.', notifyEnable: 'Enable notifications',
    someoneCalling: 'Someone is calling…', incomingCall: 'Incoming call', isCalling: (n: string) => `${n} is calling…`, answer: 'Answer', decline: 'Decline',
    busyRinging: (n: string) => `${n || 'Someone'} is calling`, inACall: 'You’re already in this call', addToCall: 'Add to this call',
    declineMsgTitle: 'Send them a quick note', cannedDecline: ['Can’t talk right now', 'In a meeting — I’ll call you back', 'Busy, try again later', 'I’ll call you shortly'],
    customMsgPh: 'Write your own message…', sendAndDecline: 'Send & decline', justDecline: 'Decline without a note', sendMsg: 'Message',
    declinedTitle: 'Call declined', declinedGeneric: 'They can’t take the call right now.', addingToCall: 'Adding them to your call…',
    callEnded: 'Call ended', callAgain: 'Call again',
    savedNameHint: 'This name is saved in this browser — tap to use a random name instead',
    femaleName: 'Female name', femaleOn: 'Female name (on)', femaleOff: 'Female name (off)',
    callLinkSet: 'You have set up a Call Me link:',
    connectFail: 'Couldn’t connect to', waitSlow: 'Still trying to connect — if this hangs, the host may be offline or the network is blocking the call.',
    rotate: 'Rotate (snaps to 45°)', moveText: 'Move', widthText: 'Drag to set width', smaller: 'Smaller', bigger: 'Bigger',
    privacy: 'All data is peer-to-peer, only the handshake uses the server.',
  },
  ar: {
    title: 'مكالمة خاصة', lead: 'اجتماعات آمنة — الفيديو والسبورة والدردشة والملفات تنتقل مباشرةً بين المتصفحات. فقط المصافحة الأولى، ولا أي بيانات، تمر بخادمنا.',
    yourName: 'اسمك', start: 'ابدأ مكالمة', askJoin: 'اطلب الانضمام', startOwn: 'ابدأ مكالمتك الخاصة بدلًا من ذلك', shuffle: 'اسم عشوائي', rememberName: 'حدّد لتذكّر اسمك', joining: 'جارٍ الاتصال…', checkingMeeting: 'جارٍ التحقق من الاجتماع…', shareInvite: 'مشاركة الدعوة',
    mic: 'المايك', cam: 'الكاميرا', screen: 'مشاركة الشاشة', stopScreen: 'إيقاف المشاركة', screenUnsupported: 'مشاركة الشاشة غير مدعومة على هذا الجهاز', screenFailed: 'فشلت مشاركة الشاشة', board: 'السبورة', chat: 'الدردشة', invite: 'دعوة', leave: 'مغادرة',
    you: 'أنت', waiting: 'بانتظار انضمام آخرين — شارك الدعوة.', clear: 'مسح', typeMsg: 'رسالة…', send: 'إرسال', noMessages: 'لا رسائل بعد', close: 'إغلاق', reconnecting: 'صامت — إعادة الاتصال…', dropFiles: 'أفلت ملفات للإرسال أو اضغط',
    maximize: 'تكبير', restore: 'استعادة', reactions: 'تفاعلات', dock: 'اللوحة', tags: 'كلمات', addTag: 'أضف كلمة…', whoReacted: 'التفاعلات',
    copied: 'تم نسخ رابط الدعوة', copy: 'نسخ الرابط', copyDone: 'تم النسخ!', shareQrUrl: 'مشاركة الرمز والرابط', shareHint: 'شارك الرابط — يظهر من يفتحه هنا لتسمح له بالدخول.',
    lobbyList: 'في غرفة الانتظار', admit: 'اسمح بالدخول', leftLobby: 'غادر', waitingHost: 'بانتظار أن يسمح لك المضيف بالدخول…', cancel: 'إلغاء',
    participants: 'المشاركون', endMeeting: 'إنهاء الاجتماع', hangUp: 'مغادرة', sendFiles: 'أفلت الملفات', dropHere: 'أفلت الملفات لمشاركتها مع الجميع', muteMe: 'اكتم صوتي', unmuteMe: 'ألغِ الكتم',
    camOn: 'تشغيل الكاميرا', camOff: 'إيقاف الكاميرا', mutedBy: 'كتم', muteThem: 'اكتم للجميع', filesTitle: 'الملفات', noPreview: 'لا معاينة — نزّل للفتح', download: 'تنزيل',
    devices: 'الأجهزة', camera: 'الكاميرا', microphone: 'الميكروفون', speaker: 'السماعة',
    hostGone: 'انقطع اتصال المضيف', endsIn: 'ينتهي الاجتماع خلال', ended: 'انتهى هذا الاجتماع أو تعذّر العثور عليه.', newCall: 'ابدأ مكالمة جديدة',
    youEnded: 'غادرت المكالمة', youEndedMeeting: 'أنهيت الاجتماع.', stillThere: (n: number) => `لا يزال ${n} من المشاركين هنا`, rejoin: 'أعد الانضمام', createNew: 'أنشئ اجتماعًا جديدًا',
    joined: 'انضمّ', left: 'غادر', editName: 'عدّل اسمك', waitingToJoin: 'بانتظار الدخول',
    notifyWhy: 'نبّهك عند انضمام أحد — حتى عندما تكون هذه النافذة في الخلفية.', notifyEnable: 'تفعيل الإشعارات',
    someoneCalling: 'شخص يتصل بك…', incomingCall: 'مكالمة واردة', isCalling: (n: string) => `${n} يتصل بك…`, answer: 'رد', decline: 'رفض',
    busyRinging: (n: string) => `${n || 'شخص'} يتصل بك`, inACall: 'أنت في هذه المكالمة بالفعل', addToCall: 'أضِفه إلى هذه المكالمة',
    declineMsgTitle: 'أرسل له ملاحظة سريعة', cannedDecline: ['لا أستطيع التحدث الآن', 'في اجتماع — سأعاود الاتصال بك', 'مشغول، حاول لاحقًا', 'سأتصل بك قريبًا'],
    customMsgPh: 'اكتب رسالتك…', sendAndDecline: 'إرسال ورفض', justDecline: 'رفض دون ملاحظة', sendMsg: 'رسالة',
    declinedTitle: 'رُفضت المكالمة', declinedGeneric: 'لا يستطيع الرد على المكالمة الآن.', addingToCall: 'جارٍ إضافته إلى مكالمتك…',
    callEnded: 'انتهت المكالمة', callAgain: 'اتصل مجددًا',
    savedNameHint: 'هذا الاسم محفوظ في هذا المتصفح — اضغط لاستخدام اسم عشوائي بدلًا منه',
    femaleName: 'اسم أنثوي', femaleOn: 'اسم أنثوي (مُفعّل)', femaleOff: 'اسم أنثوي (مُعطّل)',
    callLinkSet: 'لقد أنشأت رابط «اتصل بي»:',
    connectFail: 'تعذّر الاتصال بـ', waitSlow: 'ما زلنا نحاول الاتصال — إن طال ذلك، فقد يكون المضيف غير متصل أو الشبكة تمنع المكالمة.',
    rotate: 'تدوير (يثبُت على ٤٥°)', moveText: 'تحريك', widthText: 'اسحب لتحديد العرض', smaller: 'أصغر', bigger: 'أكبر',
    privacy: 'كل البيانات مباشرة بين الأجهزة، فقط المصافحة تستخدم الخادم.',
  },
}
export type Str = typeof STR['en']
